name: sdanet
channels:
  - nvidia
  - conda-forge
  - defaults
  - nodefaults
dependencies:
  - python=3.10
  - cuda-toolkit=12.4
  - cudnn=8.9
  # - nvcc=11.8
  - gcc=12
  - gxx=12
  - openmpi
  - libgomp
  - pip
  - pip:
      - jittor
      - opencv-python